# Generated by Django 5.2 on 2025-04-11 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_remove_shift_ta_shift_ta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='subjects',
        ),
        migrations.AddField(
            model_name='question',
            name='subjects',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='scheduling.subject'),
            preserve_default=False,
        ),
    ]
