# Generated by Django 5.2 on 2025-04-11 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_remove_question_subjects_question_subjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='subjects',
            new_name='subject',
        ),
    ]
