# Generated by Django 5.2 on 2025-04-11 23:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_rename_subjects_question_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
