# Generated by Django 5.2 on 2025-04-12 00:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_alter_school_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
