# Generated by Django 5.2 on 2025-04-12 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_alter_shift_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
