# Generated by Django 5.2 on 2025-04-14 00:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_shift_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='friday_end',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='friday_start',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='monday_end',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='monday_start',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='saturday_end',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='saturday_start',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='sunday_end',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='sunday_start',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='thursday_end',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='thursday_start',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='tuesday_end',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='tuesday_start',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='wednesday_end',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='wednesday_start',
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_ta_hours',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='time_blocks',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='subject',
            name='educators',
            field=models.ManyToManyField(blank=True, related_name='subjects', to=settings.AUTH_USER_MODEL),
        ),
    ]
