# Generated by Django 5.2 on 2025-04-14 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0009_remove_schedule_friday_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='educators',
        ),
        migrations.AddField(
            model_name='user',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='users', to='scheduling.subject'),
        ),
    ]
