# Generated by Django 5.2 on 2025-04-14 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0010_remove_subject_educators_user_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='time_blocks',
        ),
        migrations.AddField(
            model_name='schedule',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='scheduling.subject'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='educator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to=settings.AUTH_USER_MODEL),
        ),
    ]
