# Generated by Django 5.2 on 2025-04-15 13:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0014_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='SwapRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_requested', models.DateField(auto_now_add=True)),
                ('requested_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_swap_requests', to='scheduling.shift')),
                ('requested_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_swap_users', to=settings.AUTH_USER_MODEL)),
                ('requester_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests', to='scheduling.shift')),
                ('requester_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
