# Generated by Django 5.2 on 2025-04-20 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0015_alter_user_id_swaprequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='is_ta_hours',
        ),
        migrations.AddField(
            model_name='question',
            name='is_ta_hours',
            field=models.BooleanField(default=False),
        ),
    ]
