# Generated by Django 5.2 on 2025-04-20 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0016_remove_schedule_is_ta_hours_question_is_ta_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_ta_hours',
        ),
        migrations.AddField(
            model_name='subject',
            name='is_ta_hours',
            field=models.BooleanField(default=False),
        ),
    ]
