version: "3"
services:
      
  frontend:
    container_name: frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/code/src/
      - ./frontend/public:/code/public/

  backend:
    container_name: backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    volumes:
      - ./backend/backend:/code/backend/
      - ../../allauth:/code/allauth
    ports:
      - 8000:8000

  proxy:
    image: traefik:v3.0
    container_name: proxy
    ports:
      - 10000:10000
      - 80:80
      - 443:443
    volumes:
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock

  # mail:
  #   container_name: mail
  #   image: schickling/mailcatcher
  #   ports:
  #     - 1080:1080
  #     - 1025:1025
