***This repository is a copy of my final group project in Full-Stack Development at James Madison University. Below, I will be doing a technical explanation and reflective analysis on my contributions to this project.


**Project Overview
This project is a scheduling web app for educators, teaching assistants and students. It's meant for colleges and universities who want a more convenient way for TAs to choose shifts, swap shifts, and view their overall schedule. For some university programs, TAs only work for their assigned professor. In others, such as JMU's Computer Science department, TAs are required to work in general TA hours after classes, allowing shifts to be swapped. The website was created to be flexible for programs that have contraints and programs that allow shift swapping.


**Features & Technologies
*** Techlogies Used:

<b>Backend</b>:
OpenAPI - API generator
Django - Python backend framework

<b>Frontend</b>:
OpenAPI - API generator
React - library
Chakra-UI - CSS framework
Syncfusion - Javascript scheduling library

***Features Implemented:
- Student questions
  - Questions can be picked up and answered by TAs
- Permission adjustments based on the user's group (educator, TA, or student)
- TA shift requests
- TA shift swap requests
- TA schedule calendar view
- Educator schedule calendar view


**How the app works
- When you open the app, you are prompted to create an account. You may login and get an email for your login code.
- Once you login, the app asks whether you are an Educator, TA, or Student
  - Based on this selection, you will be given certain permissions
- Students can post questions for TAs to respond to
- TAs can make shift requests, shift swap requests, and answer questions posted by students
- Educators can create schedules with TA shifts for TAs to join
- All users can view the TA and Educator schedules


**My Contributions & What I Learned



**Testing and Evaluation



**What Would I do Differently?



**Setup & Usage
