defaultEntryPoints = ["http"]

[log]
level = "DEBUG"

[api]
dashboard = true

[accessLog]


[providers]
providersThrottleDuration = 10
[providers.file]
filename = "traefik.toml"
directory = "/etc/traefik/"
watch = true


[entryPoints]
[entryPoints.web]
address = ":80"
[entryPoints.websecure]
address = ":443"

[certificatesResolvers]
  [certificatesResolvers.letsencrypt.acme]
  email = "jcdonfack04@gmail.com"
  storage = "/acme.json"
  [certificatesResolvers.letsencrypt.acme.httpChallenge]
    entryPoint = "web"

[http.routers]

[http.routers.django]
service = "django"
rule = "Host(`tasync.jeromeslocallibrary.me`) && PathPrefix(`/accounts`) || PathPrefix(`/_allauth`) || PathPrefix(`/ninja`) || PathPrefix(`/drf`) || PathPrefix(`/sched_api`)"
entryPoints = ["web", "websecure"]
tls.certresolver = "letsencrypt"


[http.routers.react]
service = "react"
rule = "PathPrefix(`/`)"
entryPoints = ["web", "websecure"]
tls.certresolver = "letsencrypt"

[http.services]
[http.services.react.loadBalancer]
[[http.services.react.loadBalancer.servers]]
url = "http://frontend:3000"
[http.services.django.loadBalancer]
[[http.services.django.loadBalancer.servers]]
url = "http://backend:8000"
