/**
 * Sched API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SchedApi);
  }
}(this, function(expect, SchedApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SchedApi.DefaultApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DefaultApi', function() {
    describe('backendSchedApiViewsAddGroup', function() {
      it('should call backendSchedApiViewsAddGroup successfully', function(done) {
        //uncomment below and update the code to test backendSchedApiViewsAddGroup
        //instance.backendSchedApiViewsAddGroup(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('backendSchedApiViewsAddStudentToShift', function() {
      it('should call backendSchedApiViewsAddStudentToShift successfully', function(done) {
        //uncomment below and update the code to test backendSchedApiViewsAddStudentToShift
        //instance.backendSchedApiViewsAddStudentToShift(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('backendSchedApiViewsAddTaToShift', function() {
      it('should call backendSchedApiViewsAddTaToShift successfully', function(done) {
        //uncomment below and update the code to test backendSchedApiViewsAddTaToShift
        //instance.backendSchedApiViewsAddTaToShift(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('backendSchedApiViewsAnswerQuestion', function() {
      it('should call backendSchedApiViewsAnswerQuestion successfully', function(done) {
        //uncomment below and update the code to test backendSchedApiViewsAnswerQuestion
        //instance.backendSchedApiViewsAnswerQuestion(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('backendSchedApiViewsCommentQuestion', function() {
      it('should call backendSchedApiViewsCommentQuestion successfully', function(done) {
        //uncomment below and update the code to test backendSchedApiViewsCommentQuestion
        //instance.backendSchedApiViewsCommentQuestion(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('backendSchedApiViewsCreateQuestion', function() {
      it('should call backendSchedApiViewsCreateQuestion successfully', function(done) {
        //uncomment below and update the code to test backendSchedApiViewsCreateQuestion
        //instance.backendSchedApiViewsCreateQuestion(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('backendSchedApiViewsCreateSchedule', function() {
      it('should call backendSchedApiViewsCreateSchedule successfully', function(done) {
        //uncomment below and update the code to test backendSchedApiViewsCreateSchedule
        //instance.backendSchedApiViewsCreateSchedule(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('backendSchedApiViewsCreateSubject', function() {
      it('should call backendSchedApiViewsCreateSubject successfully', function(done) {
        //uncomment below and update the code to test backendSchedApiViewsCreateSubject
        //instance.backendSchedApiViewsCreateSubject(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('backendSchedApiViewsCreateSwapRequest', function() {
      it('should call backendSchedApiViewsCreateSwapRequest successfully', function(done) {
        //uncomment below and update the code to test backendSchedApiViewsCreateSwapRequest
        //instance.backendSchedApiViewsCreateSwapRequest(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('backendSchedApiViewsCreateTaShift', function() {
      it('should call backendSchedApiViewsCreateTaShift successfully', function(done) {
        //uncomment below and update the code to test backendSchedApiViewsCreateTaShift
        //instance.backendSchedApiViewsCreateTaShift(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('backendSchedApiViewsGetUserGroup', function() {
      it('should call backendSchedApiViewsGetUserGroup successfully', function(done) {
        //uncomment below and update the code to test backendSchedApiViewsGetUserGroup
        //instance.backendSchedApiViewsGetUserGroup(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('backendSchedApiViewsHandleSwapRequest', function() {
      it('should call backendSchedApiViewsHandleSwapRequest successfully', function(done) {
        //uncomment below and update the code to test backendSchedApiViewsHandleSwapRequest
        //instance.backendSchedApiViewsHandleSwapRequest(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('backendSchedApiViewsListAllShifts', function() {
      it('should call backendSchedApiViewsListAllShifts successfully', function(done) {
        //uncomment below and update the code to test backendSchedApiViewsListAllShifts
        //instance.backendSchedApiViewsListAllShifts(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('backendSchedApiViewsListGroups', function() {
      it('should call backendSchedApiViewsListGroups successfully', function(done) {
        //uncomment below and update the code to test backendSchedApiViewsListGroups
        //instance.backendSchedApiViewsListGroups(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('backendSchedApiViewsListIncomingSwapRequests', function() {
      it('should call backendSchedApiViewsListIncomingSwapRequests successfully', function(done) {
        //uncomment below and update the code to test backendSchedApiViewsListIncomingSwapRequests
        //instance.backendSchedApiViewsListIncomingSwapRequests(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('backendSchedApiViewsListOutgoingSwapRequests', function() {
      it('should call backendSchedApiViewsListOutgoingSwapRequests successfully', function(done) {
        //uncomment below and update the code to test backendSchedApiViewsListOutgoingSwapRequests
        //instance.backendSchedApiViewsListOutgoingSwapRequests(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('backendSchedApiViewsListQuestions', function() {
      it('should call backendSchedApiViewsListQuestions successfully', function(done) {
        //uncomment below and update the code to test backendSchedApiViewsListQuestions
        //instance.backendSchedApiViewsListQuestions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('backendSchedApiViewsListSchedules', function() {
      it('should call backendSchedApiViewsListSchedules successfully', function(done) {
        //uncomment below and update the code to test backendSchedApiViewsListSchedules
        //instance.backendSchedApiViewsListSchedules(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('backendSchedApiViewsListSchools', function() {
      it('should call backendSchedApiViewsListSchools successfully', function(done) {
        //uncomment below and update the code to test backendSchedApiViewsListSchools
        //instance.backendSchedApiViewsListSchools(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('backendSchedApiViewsListSchoolsPaginated', function() {
      it('should call backendSchedApiViewsListSchoolsPaginated successfully', function(done) {
        //uncomment below and update the code to test backendSchedApiViewsListSchoolsPaginated
        //instance.backendSchedApiViewsListSchoolsPaginated(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('backendSchedApiViewsListShiftStudents', function() {
      it('should call backendSchedApiViewsListShiftStudents successfully', function(done) {
        //uncomment below and update the code to test backendSchedApiViewsListShiftStudents
        //instance.backendSchedApiViewsListShiftStudents(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('backendSchedApiViewsListShiftTas', function() {
      it('should call backendSchedApiViewsListShiftTas successfully', function(done) {
        //uncomment below and update the code to test backendSchedApiViewsListShiftTas
        //instance.backendSchedApiViewsListShiftTas(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('backendSchedApiViewsListSubjects', function() {
      it('should call backendSchedApiViewsListSubjects successfully', function(done) {
        //uncomment below and update the code to test backendSchedApiViewsListSubjects
        //instance.backendSchedApiViewsListSubjects(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('backendSchedApiViewsListTaHourSchedule', function() {
      it('should call backendSchedApiViewsListTaHourSchedule successfully', function(done) {
        //uncomment below and update the code to test backendSchedApiViewsListTaHourSchedule
        //instance.backendSchedApiViewsListTaHourSchedule(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('backendSchedApiViewsListTaHourShift', function() {
      it('should call backendSchedApiViewsListTaHourShift successfully', function(done) {
        //uncomment below and update the code to test backendSchedApiViewsListTaHourShift
        //instance.backendSchedApiViewsListTaHourShift(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('backendSchedApiViewsListTaShifts', function() {
      it('should call backendSchedApiViewsListTaShifts successfully', function(done) {
        //uncomment below and update the code to test backendSchedApiViewsListTaShifts
        //instance.backendSchedApiViewsListTaShifts(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('backendSchedApiViewsListUserShifts', function() {
      it('should call backendSchedApiViewsListUserShifts successfully', function(done) {
        //uncomment below and update the code to test backendSchedApiViewsListUserShifts
        //instance.backendSchedApiViewsListUserShifts(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('backendSchedApiViewsListUsers', function() {
      it('should call backendSchedApiViewsListUsers successfully', function(done) {
        //uncomment below and update the code to test backendSchedApiViewsListUsers
        //instance.backendSchedApiViewsListUsers(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('backendSchedApiViewsRemoveStudentFromShift', function() {
      it('should call backendSchedApiViewsRemoveStudentFromShift successfully', function(done) {
        //uncomment below and update the code to test backendSchedApiViewsRemoveStudentFromShift
        //instance.backendSchedApiViewsRemoveStudentFromShift(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('backendSchedApiViewsRemoveTaFromShift', function() {
      it('should call backendSchedApiViewsRemoveTaFromShift successfully', function(done) {
        //uncomment below and update the code to test backendSchedApiViewsRemoveTaFromShift
        //instance.backendSchedApiViewsRemoveTaFromShift(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('backendSchedApiViewsUnanswerQuestion', function() {
      it('should call backendSchedApiViewsUnanswerQuestion successfully', function(done) {
        //uncomment below and update the code to test backendSchedApiViewsUnanswerQuestion
        //instance.backendSchedApiViewsUnanswerQuestion(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
