/**
 * Sched API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SchedApi);
  }
}(this, function(expect, SchedApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SchedApi.ShiftSchema();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ShiftSchema', function() {
    it('should create an instance of ShiftSchema', function() {
      // uncomment below and update the code to test ShiftSchema
      //var instance = new SchedApi.ShiftSchema();
      //expect(instance).to.be.a(SchedApi.ShiftSchema);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new SchedApi.ShiftSchema();
      //expect(instance).to.be();
    });

    it('should have the property schedule (base name: "schedule")', function() {
      // uncomment below and update the code to test the property schedule
      //var instance = new SchedApi.ShiftSchema();
      //expect(instance).to.be();
    });

    it('should have the property startTime (base name: "start_time")', function() {
      // uncomment below and update the code to test the property startTime
      //var instance = new SchedApi.ShiftSchema();
      //expect(instance).to.be();
    });

    it('should have the property endTime (base name: "end_time")', function() {
      // uncomment below and update the code to test the property endTime
      //var instance = new SchedApi.ShiftSchema();
      //expect(instance).to.be();
    });

    it('should have the property dayOfWeek (base name: "day_of_week")', function() {
      // uncomment below and update the code to test the property dayOfWeek
      //var instance = new SchedApi.ShiftSchema();
      //expect(instance).to.be();
    });

    it('should have the property date (base name: "date")', function() {
      // uncomment below and update the code to test the property date
      //var instance = new SchedApi.ShiftSchema();
      //expect(instance).to.be();
    });

    it('should have the property maxTa (base name: "max_ta")', function() {
      // uncomment below and update the code to test the property maxTa
      //var instance = new SchedApi.ShiftSchema();
      //expect(instance).to.be();
    });

    it('should have the property maxStudents (base name: "max_students")', function() {
      // uncomment below and update the code to test the property maxStudents
      //var instance = new SchedApi.ShiftSchema();
      //expect(instance).to.be();
    });

    it('should have the property ta (base name: "ta")', function() {
      // uncomment below and update the code to test the property ta
      //var instance = new SchedApi.ShiftSchema();
      //expect(instance).to.be();
    });

    it('should have the property students (base name: "students")', function() {
      // uncomment below and update the code to test the property students
      //var instance = new SchedApi.ShiftSchema();
      //expect(instance).to.be();
    });

  });

}));
