/**
 * Sched API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SchedApi);
  }
}(this, function(expect, SchedApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SchedApi.SwapRequestSchema();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SwapRequestSchema', function() {
    it('should create an instance of SwapRequestSchema', function() {
      // uncomment below and update the code to test SwapRequestSchema
      //var instance = new SchedApi.SwapRequestSchema();
      //expect(instance).to.be.a(SchedApi.SwapRequestSchema);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new SchedApi.SwapRequestSchema();
      //expect(instance).to.be();
    });

    it('should have the property requesterShift (base name: "requester_shift")', function() {
      // uncomment below and update the code to test the property requesterShift
      //var instance = new SchedApi.SwapRequestSchema();
      //expect(instance).to.be();
    });

    it('should have the property requestedShift (base name: "requested_shift")', function() {
      // uncomment below and update the code to test the property requestedShift
      //var instance = new SchedApi.SwapRequestSchema();
      //expect(instance).to.be();
    });

    it('should have the property requesterUser (base name: "requester_user")', function() {
      // uncomment below and update the code to test the property requesterUser
      //var instance = new SchedApi.SwapRequestSchema();
      //expect(instance).to.be();
    });

    it('should have the property requestedUser (base name: "requested_user")', function() {
      // uncomment below and update the code to test the property requestedUser
      //var instance = new SchedApi.SwapRequestSchema();
      //expect(instance).to.be();
    });

    it('should have the property dateRequested (base name: "date_requested")', function() {
      // uncomment below and update the code to test the property dateRequested
      //var instance = new SchedApi.SwapRequestSchema();
      //expect(instance).to.be();
    });

  });

}));
