/**
 * Sched API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SchedApi);
  }
}(this, function(expect, SchedApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SchedApi.UserSchema();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UserSchema', function() {
    it('should create an instance of UserSchema', function() {
      // uncomment below and update the code to test UserSchema
      //var instance = new SchedApi.UserSchema();
      //expect(instance).to.be.a(SchedApi.UserSchema);
    });

    it('should have the property username (base name: "username")', function() {
      // uncomment below and update the code to test the property username
      //var instance = new SchedApi.UserSchema();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new SchedApi.UserSchema();
      //expect(instance).to.be();
    });

    it('should have the property school (base name: "school")', function() {
      // uncomment below and update the code to test the property school
      //var instance = new SchedApi.UserSchema();
      //expect(instance).to.be();
    });

    it('should have the property subjects (base name: "subjects")', function() {
      // uncomment below and update the code to test the property subjects
      //var instance = new SchedApi.UserSchema();
      //expect(instance).to.be();
    });

  });

}));
