/**
 * Sched API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SubjectSchema from './SubjectSchema';
import UserSchema from './UserSchema';

/**
 * The ScheduleSchema model module.
 * @module model/ScheduleSchema
 * @version 1.0
 */
class ScheduleSchema {
    /**
     * Constructs a new <code>ScheduleSchema</code>.
     * @alias module:model/ScheduleSchema
     * @param id {String} 
     * @param educator {module:model/UserSchema} 
     * @param subject {module:model/SubjectSchema} 
     */
    constructor(id, educator, subject) { 
        
        ScheduleSchema.initialize(this, id, educator, subject);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, educator, subject) { 
        obj['id'] = id;
        obj['educator'] = educator;
        obj['subject'] = subject;
    }

    /**
     * Constructs a <code>ScheduleSchema</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ScheduleSchema} obj Optional instance to populate.
     * @return {module:model/ScheduleSchema} The populated <code>ScheduleSchema</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ScheduleSchema();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('educator')) {
                obj['educator'] = UserSchema.constructFromObject(data['educator']);
            }
            if (data.hasOwnProperty('subject')) {
                obj['subject'] = SubjectSchema.constructFromObject(data['subject']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ScheduleSchema</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ScheduleSchema</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ScheduleSchema.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // validate the optional field `educator`
        if (data['educator']) { // data not null
          UserSchema.validateJSON(data['educator']);
        }
        // validate the optional field `subject`
        if (data['subject']) { // data not null
          SubjectSchema.validateJSON(data['subject']);
        }

        return true;
    }


}

ScheduleSchema.RequiredProperties = ["id", "educator", "subject"];

/**
 * @member {String} id
 */
ScheduleSchema.prototype['id'] = undefined;

/**
 * @member {module:model/UserSchema} educator
 */
ScheduleSchema.prototype['educator'] = undefined;

/**
 * @member {module:model/SubjectSchema} subject
 */
ScheduleSchema.prototype['subject'] = undefined;






export default ScheduleSchema;

