/**
 * Sched API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ShiftSchemaCreate model module.
 * @module model/ShiftSchemaCreate
 * @version 1.0
 */
class ShiftSchemaCreate {
    /**
     * Constructs a new <code>ShiftSchemaCreate</code>.
     * @alias module:model/ShiftSchemaCreate
     * @param startTime {String} 
     * @param endTime {String} 
     * @param dayOfWeek {String} 
     * @param date {Date} 
     * @param maxTa {Number} 
     * @param maxStudents {Number} 
     */
    constructor(startTime, endTime, dayOfWeek, date, maxTa, maxStudents) { 
        
        ShiftSchemaCreate.initialize(this, startTime, endTime, dayOfWeek, date, maxTa, maxStudents);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, startTime, endTime, dayOfWeek, date, maxTa, maxStudents) { 
        obj['start_time'] = startTime;
        obj['end_time'] = endTime;
        obj['day_of_week'] = dayOfWeek;
        obj['date'] = date;
        obj['max_ta'] = maxTa;
        obj['max_students'] = maxStudents;
    }

    /**
     * Constructs a <code>ShiftSchemaCreate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ShiftSchemaCreate} obj Optional instance to populate.
     * @return {module:model/ShiftSchemaCreate} The populated <code>ShiftSchemaCreate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ShiftSchemaCreate();

            if (data.hasOwnProperty('start_time')) {
                obj['start_time'] = ApiClient.convertToType(data['start_time'], 'String');
            }
            if (data.hasOwnProperty('end_time')) {
                obj['end_time'] = ApiClient.convertToType(data['end_time'], 'String');
            }
            if (data.hasOwnProperty('day_of_week')) {
                obj['day_of_week'] = ApiClient.convertToType(data['day_of_week'], 'String');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
            if (data.hasOwnProperty('max_ta')) {
                obj['max_ta'] = ApiClient.convertToType(data['max_ta'], 'Number');
            }
            if (data.hasOwnProperty('max_students')) {
                obj['max_students'] = ApiClient.convertToType(data['max_students'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ShiftSchemaCreate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ShiftSchemaCreate</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ShiftSchemaCreate.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['start_time'] && !(typeof data['start_time'] === 'string' || data['start_time'] instanceof String)) {
            throw new Error("Expected the field `start_time` to be a primitive type in the JSON string but got " + data['start_time']);
        }
        // ensure the json data is a string
        if (data['end_time'] && !(typeof data['end_time'] === 'string' || data['end_time'] instanceof String)) {
            throw new Error("Expected the field `end_time` to be a primitive type in the JSON string but got " + data['end_time']);
        }
        // ensure the json data is a string
        if (data['day_of_week'] && !(typeof data['day_of_week'] === 'string' || data['day_of_week'] instanceof String)) {
            throw new Error("Expected the field `day_of_week` to be a primitive type in the JSON string but got " + data['day_of_week']);
        }

        return true;
    }


}

ShiftSchemaCreate.RequiredProperties = ["start_time", "end_time", "day_of_week", "date", "max_ta", "max_students"];

/**
 * @member {String} start_time
 */
ShiftSchemaCreate.prototype['start_time'] = undefined;

/**
 * @member {String} end_time
 */
ShiftSchemaCreate.prototype['end_time'] = undefined;

/**
 * @member {String} day_of_week
 */
ShiftSchemaCreate.prototype['day_of_week'] = undefined;

/**
 * @member {Date} date
 */
ShiftSchemaCreate.prototype['date'] = undefined;

/**
 * @member {Number} max_ta
 */
ShiftSchemaCreate.prototype['max_ta'] = undefined;

/**
 * @member {Number} max_students
 */
ShiftSchemaCreate.prototype['max_students'] = undefined;






export default ShiftSchemaCreate;

