/**
 * Sched API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ShiftSchema from './ShiftSchema';
import UserSchema from './UserSchema';

/**
 * The SwapRequestSchema model module.
 * @module model/SwapRequestSchema
 * @version 1.0
 */
class SwapRequestSchema {
    /**
     * Constructs a new <code>SwapRequestSchema</code>.
     * @alias module:model/SwapRequestSchema
     * @param id {String} 
     * @param fromShift {module:model/ShiftSchema} 
     * @param toShift {module:model/ShiftSchema} 
     * @param fromUser {module:model/UserSchema} 
     * @param toUser {module:model/UserSchema} 
     * @param dateRequested {Date} 
     */
    constructor(id, fromShift, toShift, fromUser, toUser, dateRequested) { 
        
        SwapRequestSchema.initialize(this, id, fromShift, toShift, fromUser, toUser, dateRequested);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, fromShift, toShift, fromUser, toUser, dateRequested) { 
        obj['id'] = id;
        obj['from_shift'] = fromShift;
        obj['to_shift'] = toShift;
        obj['from_user'] = fromUser;
        obj['to_user'] = toUser;
        obj['date_requested'] = dateRequested;
    }

    /**
     * Constructs a <code>SwapRequestSchema</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SwapRequestSchema} obj Optional instance to populate.
     * @return {module:model/SwapRequestSchema} The populated <code>SwapRequestSchema</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SwapRequestSchema();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('from_shift')) {
                obj['from_shift'] = ShiftSchema.constructFromObject(data['from_shift']);
            }
            if (data.hasOwnProperty('to_shift')) {
                obj['to_shift'] = ShiftSchema.constructFromObject(data['to_shift']);
            }
            if (data.hasOwnProperty('from_user')) {
                obj['from_user'] = UserSchema.constructFromObject(data['from_user']);
            }
            if (data.hasOwnProperty('to_user')) {
                obj['to_user'] = UserSchema.constructFromObject(data['to_user']);
            }
            if (data.hasOwnProperty('date_requested')) {
                obj['date_requested'] = ApiClient.convertToType(data['date_requested'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SwapRequestSchema</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SwapRequestSchema</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SwapRequestSchema.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // validate the optional field `from_shift`
        if (data['from_shift']) { // data not null
          ShiftSchema.validateJSON(data['from_shift']);
        }
        // validate the optional field `to_shift`
        if (data['to_shift']) { // data not null
          ShiftSchema.validateJSON(data['to_shift']);
        }
        // validate the optional field `from_user`
        if (data['from_user']) { // data not null
          UserSchema.validateJSON(data['from_user']);
        }
        // validate the optional field `to_user`
        if (data['to_user']) { // data not null
          UserSchema.validateJSON(data['to_user']);
        }

        return true;
    }


}

SwapRequestSchema.RequiredProperties = ["id", "from_shift", "to_shift", "from_user", "to_user", "date_requested"];

/**
 * @member {String} id
 */
SwapRequestSchema.prototype['id'] = undefined;

/**
 * @member {module:model/ShiftSchema} from_shift
 */
SwapRequestSchema.prototype['from_shift'] = undefined;

/**
 * @member {module:model/ShiftSchema} to_shift
 */
SwapRequestSchema.prototype['to_shift'] = undefined;

/**
 * @member {module:model/UserSchema} from_user
 */
SwapRequestSchema.prototype['from_user'] = undefined;

/**
 * @member {module:model/UserSchema} to_user
 */
SwapRequestSchema.prototype['to_user'] = undefined;

/**
 * @member {Date} date_requested
 */
SwapRequestSchema.prototype['date_requested'] = undefined;






export default SwapRequestSchema;

