# Generated by Django 5.2 on 2025-04-10 23:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_subject_alter_user_school_schedule_shift_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='ta',
        ),
        migrations.AddField(
            model_name='shift',
            name='ta',
            field=models.ManyToManyField(blank=True, related_name='ta_shift', to=settings.AUTH_USER_MODEL),
        ),
    ]
