# Generated by Django 5.2 on 2025-04-15 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0011_remove_schedule_time_blocks_schedule_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_asked',
            field=models.DateField(auto_now_add=True),
        ),
    ]
