/**
 * Sched API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SchedApi);
  }
}(this, function(expect, SchedApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SchedApi.DefaultApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DefaultApi', function() {
    describe('backendSchedApiViewsAnswerQuestion', function() {
      it('should call backendSchedApiViewsAnswerQuestion successfully', function(done) {
        //uncomment below and update the code to test backendSchedApiViewsAnswerQuestion
        //instance.backendSchedApiViewsAnswerQuestion(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('backendSchedApiViewsCommentQuestion', function() {
      it('should call backendSchedApiViewsCommentQuestion successfully', function(done) {
        //uncomment below and update the code to test backendSchedApiViewsCommentQuestion
        //instance.backendSchedApiViewsCommentQuestion(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('backendSchedApiViewsCreateQuestion', function() {
      it('should call backendSchedApiViewsCreateQuestion successfully', function(done) {
        //uncomment below and update the code to test backendSchedApiViewsCreateQuestion
        //instance.backendSchedApiViewsCreateQuestion(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('backendSchedApiViewsCreateSchedule', function() {
      it('should call backendSchedApiViewsCreateSchedule successfully', function(done) {
        //uncomment below and update the code to test backendSchedApiViewsCreateSchedule
        //instance.backendSchedApiViewsCreateSchedule(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('backendSchedApiViewsCreateSubject', function() {
      it('should call backendSchedApiViewsCreateSubject successfully', function(done) {
        //uncomment below and update the code to test backendSchedApiViewsCreateSubject
        //instance.backendSchedApiViewsCreateSubject(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('backendSchedApiViewsCreateSwapRequest', function() {
      it('should call backendSchedApiViewsCreateSwapRequest successfully', function(done) {
        //uncomment below and update the code to test backendSchedApiViewsCreateSwapRequest
        //instance.backendSchedApiViewsCreateSwapRequest(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('backendSchedApiViewsCreateTaShift', function() {
      it('should call backendSchedApiViewsCreateTaShift successfully', function(done) {
        //uncomment below and update the code to test backendSchedApiViewsCreateTaShift
        //instance.backendSchedApiViewsCreateTaShift(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('backendSchedApiViewsListQuestions', function() {
      it('should call backendSchedApiViewsListQuestions successfully', function(done) {
        //uncomment below and update the code to test backendSchedApiViewsListQuestions
        //instance.backendSchedApiViewsListQuestions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('backendSchedApiViewsListSchools', function() {
      it('should call backendSchedApiViewsListSchools successfully', function(done) {
        //uncomment below and update the code to test backendSchedApiViewsListSchools
        //instance.backendSchedApiViewsListSchools(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('backendSchedApiViewsListSchoolsPaginated', function() {
      it('should call backendSchedApiViewsListSchoolsPaginated successfully', function(done) {
        //uncomment below and update the code to test backendSchedApiViewsListSchoolsPaginated
        //instance.backendSchedApiViewsListSchoolsPaginated(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('backendSchedApiViewsListTaShifts', function() {
      it('should call backendSchedApiViewsListTaShifts successfully', function(done) {
        //uncomment below and update the code to test backendSchedApiViewsListTaShifts
        //instance.backendSchedApiViewsListTaShifts(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
